# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/velo6raptor/Téléchargements/clion-2017.3.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/velo6raptor/Téléchargements/clion-2017.3.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/velo6raptor/delivery/PSU/PSU_zappy_2017

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/velo6raptor/delivery/PSU/PSU_zappy_2017

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/velo6raptor/Téléchargements/clion-2017.3.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/velo6raptor/Téléchargements/clion-2017.3.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/velo6raptor/delivery/PSU/PSU_zappy_2017/CMakeFiles /home/velo6raptor/delivery/PSU/PSU_zappy_2017/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/velo6raptor/delivery/PSU/PSU_zappy_2017/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

Src/Main.o: Src/Main.cpp.o

.PHONY : Src/Main.o

# target to build an object file
Src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.o
.PHONY : Src/Main.cpp.o

Src/Main.i: Src/Main.cpp.i

.PHONY : Src/Main.i

# target to preprocess a source file
Src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.i
.PHONY : Src/Main.cpp.i

Src/Main.s: Src/Main.cpp.s

.PHONY : Src/Main.s

# target to generate assembly for a file
Src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.s
.PHONY : Src/Main.cpp.s

Src/Tools/Thread.o: Src/Tools/Thread.cpp.o

.PHONY : Src/Tools/Thread.o

# target to build an object file
Src/Tools/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.o
.PHONY : Src/Tools/Thread.cpp.o

Src/Tools/Thread.i: Src/Tools/Thread.cpp.i

.PHONY : Src/Tools/Thread.i

# target to preprocess a source file
Src/Tools/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.i
.PHONY : Src/Tools/Thread.cpp.i

Src/Tools/Thread.s: Src/Tools/Thread.cpp.s

.PHONY : Src/Tools/Thread.s

# target to generate assembly for a file
Src/Tools/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.s
.PHONY : Src/Tools/Thread.cpp.s

Src/client/Auth.o: Src/client/Auth.cpp.o

.PHONY : Src/client/Auth.o

# target to build an object file
Src/client/Auth.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.o
.PHONY : Src/client/Auth.cpp.o

Src/client/Auth.i: Src/client/Auth.cpp.i

.PHONY : Src/client/Auth.i

# target to preprocess a source file
Src/client/Auth.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.i
.PHONY : Src/client/Auth.cpp.i

Src/client/Auth.s: Src/client/Auth.cpp.s

.PHONY : Src/client/Auth.s

# target to generate assembly for a file
Src/client/Auth.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.s
.PHONY : Src/client/Auth.cpp.s

Src/client/Gui.o: Src/client/Gui.cpp.o

.PHONY : Src/client/Gui.o

# target to build an object file
Src/client/Gui.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.o
.PHONY : Src/client/Gui.cpp.o

Src/client/Gui.i: Src/client/Gui.cpp.i

.PHONY : Src/client/Gui.i

# target to preprocess a source file
Src/client/Gui.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.i
.PHONY : Src/client/Gui.cpp.i

Src/client/Gui.s: Src/client/Gui.cpp.s

.PHONY : Src/client/Gui.s

# target to generate assembly for a file
Src/client/Gui.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.s
.PHONY : Src/client/Gui.cpp.s

Src/client/Gui/Animation/Modal.o: Src/client/Gui/Animation/Modal.cpp.o

.PHONY : Src/client/Gui/Animation/Modal.o

# target to build an object file
Src/client/Gui/Animation/Modal.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.o
.PHONY : Src/client/Gui/Animation/Modal.cpp.o

Src/client/Gui/Animation/Modal.i: Src/client/Gui/Animation/Modal.cpp.i

.PHONY : Src/client/Gui/Animation/Modal.i

# target to preprocess a source file
Src/client/Gui/Animation/Modal.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.i
.PHONY : Src/client/Gui/Animation/Modal.cpp.i

Src/client/Gui/Animation/Modal.s: Src/client/Gui/Animation/Modal.cpp.s

.PHONY : Src/client/Gui/Animation/Modal.s

# target to generate assembly for a file
Src/client/Gui/Animation/Modal.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.s
.PHONY : Src/client/Gui/Animation/Modal.cpp.s

Src/client/Gui/ObjectSFML/AbstractObjectSFML.o: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.o

# target to build an object file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o

Src/client/Gui/ObjectSFML/AbstractObjectSFML.i: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i

Src/client/Gui/ObjectSFML/AbstractObjectSFML.s: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s

Src/client/Gui/ObjectSFML/Circle.o: Src/client/Gui/ObjectSFML/Circle.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Circle.o

# target to build an object file
Src/client/Gui/ObjectSFML/Circle.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.o

Src/client/Gui/ObjectSFML/Circle.i: Src/client/Gui/ObjectSFML/Circle.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Circle.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Circle.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.i

Src/client/Gui/ObjectSFML/Circle.s: Src/client/Gui/ObjectSFML/Circle.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Circle.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Circle.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.s

Src/client/Gui/ObjectSFML/Container.o: Src/client/Gui/ObjectSFML/Container.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Container.o

# target to build an object file
Src/client/Gui/ObjectSFML/Container.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.o

Src/client/Gui/ObjectSFML/Container.i: Src/client/Gui/ObjectSFML/Container.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Container.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Container.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.i

Src/client/Gui/ObjectSFML/Container.s: Src/client/Gui/ObjectSFML/Container.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Container.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Container.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.s

Src/client/Gui/ObjectSFML/Sprite.o: Src/client/Gui/ObjectSFML/Sprite.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Sprite.o

# target to build an object file
Src/client/Gui/ObjectSFML/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.o

Src/client/Gui/ObjectSFML/Sprite.i: Src/client/Gui/ObjectSFML/Sprite.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Sprite.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.i

Src/client/Gui/ObjectSFML/Sprite.s: Src/client/Gui/ObjectSFML/Sprite.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Sprite.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.s

Src/client/Gui/ObjectSFML/Square.o: Src/client/Gui/ObjectSFML/Square.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Square.o

# target to build an object file
Src/client/Gui/ObjectSFML/Square.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.o

Src/client/Gui/ObjectSFML/Square.i: Src/client/Gui/ObjectSFML/Square.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Square.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Square.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.i

Src/client/Gui/ObjectSFML/Square.s: Src/client/Gui/ObjectSFML/Square.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Square.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Square.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.s

Src/client/Gui/ObjectSFML/Text.o: Src/client/Gui/ObjectSFML/Text.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Text.o

# target to build an object file
Src/client/Gui/ObjectSFML/Text.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.o

Src/client/Gui/ObjectSFML/Text.i: Src/client/Gui/ObjectSFML/Text.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Text.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Text.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.i

Src/client/Gui/ObjectSFML/Text.s: Src/client/Gui/ObjectSFML/Text.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Text.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Text.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.s

Src/client/Gui/ObjectSFML/TextInput.o: Src/client/Gui/ObjectSFML/TextInput.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/TextInput.o

# target to build an object file
Src/client/Gui/ObjectSFML/TextInput.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.o

Src/client/Gui/ObjectSFML/TextInput.i: Src/client/Gui/ObjectSFML/TextInput.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/TextInput.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/TextInput.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.i

Src/client/Gui/ObjectSFML/TextInput.s: Src/client/Gui/ObjectSFML/TextInput.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/TextInput.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/TextInput.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.s

Src/client/Gui/SFML_monitor.o: Src/client/Gui/SFML_monitor.cpp.o

.PHONY : Src/client/Gui/SFML_monitor.o

# target to build an object file
Src/client/Gui/SFML_monitor.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.o
.PHONY : Src/client/Gui/SFML_monitor.cpp.o

Src/client/Gui/SFML_monitor.i: Src/client/Gui/SFML_monitor.cpp.i

.PHONY : Src/client/Gui/SFML_monitor.i

# target to preprocess a source file
Src/client/Gui/SFML_monitor.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.i
.PHONY : Src/client/Gui/SFML_monitor.cpp.i

Src/client/Gui/SFML_monitor.s: Src/client/Gui/SFML_monitor.cpp.s

.PHONY : Src/client/Gui/SFML_monitor.s

# target to generate assembly for a file
Src/client/Gui/SFML_monitor.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.s
.PHONY : Src/client/Gui/SFML_monitor.cpp.s

Src/client/GuiTexture.o: Src/client/GuiTexture.cpp.o

.PHONY : Src/client/GuiTexture.o

# target to build an object file
Src/client/GuiTexture.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/GuiTexture.cpp.o
.PHONY : Src/client/GuiTexture.cpp.o

Src/client/GuiTexture.i: Src/client/GuiTexture.cpp.i

.PHONY : Src/client/GuiTexture.i

# target to preprocess a source file
Src/client/GuiTexture.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/GuiTexture.cpp.i
.PHONY : Src/client/GuiTexture.cpp.i

Src/client/GuiTexture.s: Src/client/GuiTexture.cpp.s

.PHONY : Src/client/GuiTexture.s

# target to generate assembly for a file
Src/client/GuiTexture.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/GuiTexture.cpp.s
.PHONY : Src/client/GuiTexture.cpp.s

Src/client/ManageDisplay.o: Src/client/ManageDisplay.cpp.o

.PHONY : Src/client/ManageDisplay.o

# target to build an object file
Src/client/ManageDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.o
.PHONY : Src/client/ManageDisplay.cpp.o

Src/client/ManageDisplay.i: Src/client/ManageDisplay.cpp.i

.PHONY : Src/client/ManageDisplay.i

# target to preprocess a source file
Src/client/ManageDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.i
.PHONY : Src/client/ManageDisplay.cpp.i

Src/client/ManageDisplay.s: Src/client/ManageDisplay.cpp.s

.PHONY : Src/client/ManageDisplay.s

# target to generate assembly for a file
Src/client/ManageDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.s
.PHONY : Src/client/ManageDisplay.cpp.s

Src/client/ManageServer.o: Src/client/ManageServer.cpp.o

.PHONY : Src/client/ManageServer.o

# target to build an object file
Src/client/ManageServer.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.o
.PHONY : Src/client/ManageServer.cpp.o

Src/client/ManageServer.i: Src/client/ManageServer.cpp.i

.PHONY : Src/client/ManageServer.i

# target to preprocess a source file
Src/client/ManageServer.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.i
.PHONY : Src/client/ManageServer.cpp.i

Src/client/ManageServer.s: Src/client/ManageServer.cpp.s

.PHONY : Src/client/ManageServer.s

# target to generate assembly for a file
Src/client/ManageServer.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.s
.PHONY : Src/client/ManageServer.cpp.s

Src/client/Map.o: Src/client/Map.cpp.o

.PHONY : Src/client/Map.o

# target to build an object file
Src/client/Map.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.o
.PHONY : Src/client/Map.cpp.o

Src/client/Map.i: Src/client/Map.cpp.i

.PHONY : Src/client/Map.i

# target to preprocess a source file
Src/client/Map.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.i
.PHONY : Src/client/Map.cpp.i

Src/client/Map.s: Src/client/Map.cpp.s

.PHONY : Src/client/Map.s

# target to generate assembly for a file
Src/client/Map.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.s
.PHONY : Src/client/Map.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... Src/Main.o"
	@echo "... Src/Main.i"
	@echo "... Src/Main.s"
	@echo "... Src/Tools/Thread.o"
	@echo "... Src/Tools/Thread.i"
	@echo "... Src/Tools/Thread.s"
	@echo "... Src/client/Auth.o"
	@echo "... Src/client/Auth.i"
	@echo "... Src/client/Auth.s"
	@echo "... Src/client/Gui.o"
	@echo "... Src/client/Gui.i"
	@echo "... Src/client/Gui.s"
	@echo "... Src/client/Gui/Animation/Modal.o"
	@echo "... Src/client/Gui/Animation/Modal.i"
	@echo "... Src/client/Gui/Animation/Modal.s"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.o"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.i"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.s"
	@echo "... Src/client/Gui/ObjectSFML/Circle.o"
	@echo "... Src/client/Gui/ObjectSFML/Circle.i"
	@echo "... Src/client/Gui/ObjectSFML/Circle.s"
	@echo "... Src/client/Gui/ObjectSFML/Container.o"
	@echo "... Src/client/Gui/ObjectSFML/Container.i"
	@echo "... Src/client/Gui/ObjectSFML/Container.s"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.o"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.i"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.s"
	@echo "... Src/client/Gui/ObjectSFML/Square.o"
	@echo "... Src/client/Gui/ObjectSFML/Square.i"
	@echo "... Src/client/Gui/ObjectSFML/Square.s"
	@echo "... Src/client/Gui/ObjectSFML/Text.o"
	@echo "... Src/client/Gui/ObjectSFML/Text.i"
	@echo "... Src/client/Gui/ObjectSFML/Text.s"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.o"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.i"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.s"
	@echo "... Src/client/Gui/SFML_monitor.o"
	@echo "... Src/client/Gui/SFML_monitor.i"
	@echo "... Src/client/Gui/SFML_monitor.s"
	@echo "... Src/client/GuiTexture.o"
	@echo "... Src/client/GuiTexture.i"
	@echo "... Src/client/GuiTexture.s"
	@echo "... Src/client/ManageDisplay.o"
	@echo "... Src/client/ManageDisplay.i"
	@echo "... Src/client/ManageDisplay.s"
	@echo "... Src/client/ManageServer.o"
	@echo "... Src/client/ManageServer.i"
	@echo "... Src/client/ManageServer.s"
	@echo "... Src/client/Map.o"
	@echo "... Src/client/Map.i"
	@echo "... Src/client/Map.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

