# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wisenoa/NikeBienTaMere/PSU_zappy_2017

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wisenoa/NikeBienTaMere/PSU_zappy_2017

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wisenoa/NikeBienTaMere/PSU_zappy_2017/CMakeFiles /home/wisenoa/NikeBienTaMere/PSU_zappy_2017/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wisenoa/NikeBienTaMere/PSU_zappy_2017/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named zappy_server

# Build rule for target.
zappy_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zappy_server
.PHONY : zappy_server

# fast build rule for target.
zappy_server/fast:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/build
.PHONY : zappy_server/fast

Src/CstringArray.o: Src/CstringArray.cpp.o

.PHONY : Src/CstringArray.o

# target to build an object file
Src/CstringArray.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/CstringArray.cpp.o
.PHONY : Src/CstringArray.cpp.o

Src/CstringArray.i: Src/CstringArray.cpp.i

.PHONY : Src/CstringArray.i

# target to preprocess a source file
Src/CstringArray.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/CstringArray.cpp.i
.PHONY : Src/CstringArray.cpp.i

Src/CstringArray.s: Src/CstringArray.cpp.s

.PHONY : Src/CstringArray.s

# target to generate assembly for a file
Src/CstringArray.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/CstringArray.cpp.s
.PHONY : Src/CstringArray.cpp.s

Src/Entity/AMotionShape.o: Src/Entity/AMotionShape.cpp.o

.PHONY : Src/Entity/AMotionShape.o

# target to build an object file
Src/Entity/AMotionShape.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/AMotionShape.cpp.o
.PHONY : Src/Entity/AMotionShape.cpp.o

Src/Entity/AMotionShape.i: Src/Entity/AMotionShape.cpp.i

.PHONY : Src/Entity/AMotionShape.i

# target to preprocess a source file
Src/Entity/AMotionShape.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/AMotionShape.cpp.i
.PHONY : Src/Entity/AMotionShape.cpp.i

Src/Entity/AMotionShape.s: Src/Entity/AMotionShape.cpp.s

.PHONY : Src/Entity/AMotionShape.s

# target to generate assembly for a file
Src/Entity/AMotionShape.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/AMotionShape.cpp.s
.PHONY : Src/Entity/AMotionShape.cpp.s

Src/Entity/ARectangleShape.o: Src/Entity/ARectangleShape.cpp.o

.PHONY : Src/Entity/ARectangleShape.o

# target to build an object file
Src/Entity/ARectangleShape.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/ARectangleShape.cpp.o
.PHONY : Src/Entity/ARectangleShape.cpp.o

Src/Entity/ARectangleShape.i: Src/Entity/ARectangleShape.cpp.i

.PHONY : Src/Entity/ARectangleShape.i

# target to preprocess a source file
Src/Entity/ARectangleShape.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/ARectangleShape.cpp.i
.PHONY : Src/Entity/ARectangleShape.cpp.i

Src/Entity/ARectangleShape.s: Src/Entity/ARectangleShape.cpp.s

.PHONY : Src/Entity/ARectangleShape.s

# target to generate assembly for a file
Src/Entity/ARectangleShape.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/ARectangleShape.cpp.s
.PHONY : Src/Entity/ARectangleShape.cpp.s

Src/Entity/Cell.o: Src/Entity/Cell.cpp.o

.PHONY : Src/Entity/Cell.o

# target to build an object file
Src/Entity/Cell.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Cell.cpp.o
.PHONY : Src/Entity/Cell.cpp.o

Src/Entity/Cell.i: Src/Entity/Cell.cpp.i

.PHONY : Src/Entity/Cell.i

# target to preprocess a source file
Src/Entity/Cell.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Cell.cpp.i
.PHONY : Src/Entity/Cell.cpp.i

Src/Entity/Cell.s: Src/Entity/Cell.cpp.s

.PHONY : Src/Entity/Cell.s

# target to generate assembly for a file
Src/Entity/Cell.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Cell.cpp.s
.PHONY : Src/Entity/Cell.cpp.s

Src/Entity/Character.o: Src/Entity/Character.cpp.o

.PHONY : Src/Entity/Character.o

# target to build an object file
Src/Entity/Character.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Character.cpp.o
.PHONY : Src/Entity/Character.cpp.o

Src/Entity/Character.i: Src/Entity/Character.cpp.i

.PHONY : Src/Entity/Character.i

# target to preprocess a source file
Src/Entity/Character.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Character.cpp.i
.PHONY : Src/Entity/Character.cpp.i

Src/Entity/Character.s: Src/Entity/Character.cpp.s

.PHONY : Src/Entity/Character.s

# target to generate assembly for a file
Src/Entity/Character.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Character.cpp.s
.PHONY : Src/Entity/Character.cpp.s

Src/Entity/Water.o: Src/Entity/Water.cpp.o

.PHONY : Src/Entity/Water.o

# target to build an object file
Src/Entity/Water.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Water.cpp.o
.PHONY : Src/Entity/Water.cpp.o

Src/Entity/Water.i: Src/Entity/Water.cpp.i

.PHONY : Src/Entity/Water.i

# target to preprocess a source file
Src/Entity/Water.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Water.cpp.i
.PHONY : Src/Entity/Water.cpp.i

Src/Entity/Water.s: Src/Entity/Water.cpp.s

.PHONY : Src/Entity/Water.s

# target to generate assembly for a file
Src/Entity/Water.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Entity/Water.cpp.s
.PHONY : Src/Entity/Water.cpp.s

Src/Grid.o: Src/Grid.cpp.o

.PHONY : Src/Grid.o

# target to build an object file
Src/Grid.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Grid.cpp.o
.PHONY : Src/Grid.cpp.o

Src/Grid.i: Src/Grid.cpp.i

.PHONY : Src/Grid.i

# target to preprocess a source file
Src/Grid.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Grid.cpp.i
.PHONY : Src/Grid.cpp.i

Src/Grid.s: Src/Grid.cpp.s

.PHONY : Src/Grid.s

# target to generate assembly for a file
Src/Grid.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Grid.cpp.s
.PHONY : Src/Grid.cpp.s

Src/Main.o: Src/Main.cpp.o

.PHONY : Src/Main.o

# target to build an object file
Src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.o
.PHONY : Src/Main.cpp.o

Src/Main.i: Src/Main.cpp.i

.PHONY : Src/Main.i

# target to preprocess a source file
Src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.i
.PHONY : Src/Main.cpp.i

Src/Main.s: Src/Main.cpp.s

.PHONY : Src/Main.s

# target to generate assembly for a file
Src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Main.cpp.s
.PHONY : Src/Main.cpp.s

Src/ParseEnqueueMap.o: Src/ParseEnqueueMap.cpp.o

.PHONY : Src/ParseEnqueueMap.o

# target to build an object file
Src/ParseEnqueueMap.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/ParseEnqueueMap.cpp.o
.PHONY : Src/ParseEnqueueMap.cpp.o

Src/ParseEnqueueMap.i: Src/ParseEnqueueMap.cpp.i

.PHONY : Src/ParseEnqueueMap.i

# target to preprocess a source file
Src/ParseEnqueueMap.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/ParseEnqueueMap.cpp.i
.PHONY : Src/ParseEnqueueMap.cpp.i

Src/ParseEnqueueMap.s: Src/ParseEnqueueMap.cpp.s

.PHONY : Src/ParseEnqueueMap.s

# target to generate assembly for a file
Src/ParseEnqueueMap.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/ParseEnqueueMap.cpp.s
.PHONY : Src/ParseEnqueueMap.cpp.s

Src/SfmlTool.o: Src/SfmlTool.cpp.o

.PHONY : Src/SfmlTool.o

# target to build an object file
Src/SfmlTool.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/SfmlTool.cpp.o
.PHONY : Src/SfmlTool.cpp.o

Src/SfmlTool.i: Src/SfmlTool.cpp.i

.PHONY : Src/SfmlTool.i

# target to preprocess a source file
Src/SfmlTool.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/SfmlTool.cpp.i
.PHONY : Src/SfmlTool.cpp.i

Src/SfmlTool.s: Src/SfmlTool.cpp.s

.PHONY : Src/SfmlTool.s

# target to generate assembly for a file
Src/SfmlTool.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/SfmlTool.cpp.s
.PHONY : Src/SfmlTool.cpp.s

Src/Text/AText.o: Src/Text/AText.cpp.o

.PHONY : Src/Text/AText.o

# target to build an object file
Src/Text/AText.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/AText.cpp.o
.PHONY : Src/Text/AText.cpp.o

Src/Text/AText.i: Src/Text/AText.cpp.i

.PHONY : Src/Text/AText.i

# target to preprocess a source file
Src/Text/AText.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/AText.cpp.i
.PHONY : Src/Text/AText.cpp.i

Src/Text/AText.s: Src/Text/AText.cpp.s

.PHONY : Src/Text/AText.s

# target to generate assembly for a file
Src/Text/AText.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/AText.cpp.s
.PHONY : Src/Text/AText.cpp.s

Src/Text/GameText.o: Src/Text/GameText.cpp.o

.PHONY : Src/Text/GameText.o

# target to build an object file
Src/Text/GameText.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/GameText.cpp.o
.PHONY : Src/Text/GameText.cpp.o

Src/Text/GameText.i: Src/Text/GameText.cpp.i

.PHONY : Src/Text/GameText.i

# target to preprocess a source file
Src/Text/GameText.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/GameText.cpp.i
.PHONY : Src/Text/GameText.cpp.i

Src/Text/GameText.s: Src/Text/GameText.cpp.s

.PHONY : Src/Text/GameText.s

# target to generate assembly for a file
Src/Text/GameText.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Text/GameText.cpp.s
.PHONY : Src/Text/GameText.cpp.s

Src/Tools/Thread.o: Src/Tools/Thread.cpp.o

.PHONY : Src/Tools/Thread.o

# target to build an object file
Src/Tools/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.o
.PHONY : Src/Tools/Thread.cpp.o

Src/Tools/Thread.i: Src/Tools/Thread.cpp.i

.PHONY : Src/Tools/Thread.i

# target to preprocess a source file
Src/Tools/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.i
.PHONY : Src/Tools/Thread.cpp.i

Src/Tools/Thread.s: Src/Tools/Thread.cpp.s

.PHONY : Src/Tools/Thread.s

# target to generate assembly for a file
Src/Tools/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/Tools/Thread.cpp.s
.PHONY : Src/Tools/Thread.cpp.s

Src/WindowInfo.o: Src/WindowInfo.cpp.o

.PHONY : Src/WindowInfo.o

# target to build an object file
Src/WindowInfo.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/WindowInfo.cpp.o
.PHONY : Src/WindowInfo.cpp.o

Src/WindowInfo.i: Src/WindowInfo.cpp.i

.PHONY : Src/WindowInfo.i

# target to preprocess a source file
Src/WindowInfo.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/WindowInfo.cpp.i
.PHONY : Src/WindowInfo.cpp.i

Src/WindowInfo.s: Src/WindowInfo.cpp.s

.PHONY : Src/WindowInfo.s

# target to generate assembly for a file
Src/WindowInfo.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/WindowInfo.cpp.s
.PHONY : Src/WindowInfo.cpp.s

Src/client/Auth.o: Src/client/Auth.cpp.o

.PHONY : Src/client/Auth.o

# target to build an object file
Src/client/Auth.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.o
.PHONY : Src/client/Auth.cpp.o

Src/client/Auth.i: Src/client/Auth.cpp.i

.PHONY : Src/client/Auth.i

# target to preprocess a source file
Src/client/Auth.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.i
.PHONY : Src/client/Auth.cpp.i

Src/client/Auth.s: Src/client/Auth.cpp.s

.PHONY : Src/client/Auth.s

# target to generate assembly for a file
Src/client/Auth.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Auth.cpp.s
.PHONY : Src/client/Auth.cpp.s

Src/client/Communication.o: Src/client/Communication.cpp.o

.PHONY : Src/client/Communication.o

# target to build an object file
Src/client/Communication.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Communication.cpp.o
.PHONY : Src/client/Communication.cpp.o

Src/client/Communication.i: Src/client/Communication.cpp.i

.PHONY : Src/client/Communication.i

# target to preprocess a source file
Src/client/Communication.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Communication.cpp.i
.PHONY : Src/client/Communication.cpp.i

Src/client/Communication.s: Src/client/Communication.cpp.s

.PHONY : Src/client/Communication.s

# target to generate assembly for a file
Src/client/Communication.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Communication.cpp.s
.PHONY : Src/client/Communication.cpp.s

Src/client/Gui.o: Src/client/Gui.cpp.o

.PHONY : Src/client/Gui.o

# target to build an object file
Src/client/Gui.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.o
.PHONY : Src/client/Gui.cpp.o

Src/client/Gui.i: Src/client/Gui.cpp.i

.PHONY : Src/client/Gui.i

# target to preprocess a source file
Src/client/Gui.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.i
.PHONY : Src/client/Gui.cpp.i

Src/client/Gui.s: Src/client/Gui.cpp.s

.PHONY : Src/client/Gui.s

# target to generate assembly for a file
Src/client/Gui.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui.cpp.s
.PHONY : Src/client/Gui.cpp.s

Src/client/Gui/Animation/Modal.o: Src/client/Gui/Animation/Modal.cpp.o

.PHONY : Src/client/Gui/Animation/Modal.o

# target to build an object file
Src/client/Gui/Animation/Modal.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.o
.PHONY : Src/client/Gui/Animation/Modal.cpp.o

Src/client/Gui/Animation/Modal.i: Src/client/Gui/Animation/Modal.cpp.i

.PHONY : Src/client/Gui/Animation/Modal.i

# target to preprocess a source file
Src/client/Gui/Animation/Modal.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.i
.PHONY : Src/client/Gui/Animation/Modal.cpp.i

Src/client/Gui/Animation/Modal.s: Src/client/Gui/Animation/Modal.cpp.s

.PHONY : Src/client/Gui/Animation/Modal.s

# target to generate assembly for a file
Src/client/Gui/Animation/Modal.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/Animation/Modal.cpp.s
.PHONY : Src/client/Gui/Animation/Modal.cpp.s

Src/client/Gui/ObjectSFML/AbstractObjectSFML.o: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.o

# target to build an object file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.o

Src/client/Gui/ObjectSFML/AbstractObjectSFML.i: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.i

Src/client/Gui/ObjectSFML/AbstractObjectSFML.s: Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/AbstractObjectSFML.cpp.s

Src/client/Gui/ObjectSFML/Circle.o: Src/client/Gui/ObjectSFML/Circle.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Circle.o

# target to build an object file
Src/client/Gui/ObjectSFML/Circle.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.o

Src/client/Gui/ObjectSFML/Circle.i: Src/client/Gui/ObjectSFML/Circle.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Circle.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Circle.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.i

Src/client/Gui/ObjectSFML/Circle.s: Src/client/Gui/ObjectSFML/Circle.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Circle.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Circle.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Circle.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Circle.cpp.s

Src/client/Gui/ObjectSFML/Container.o: Src/client/Gui/ObjectSFML/Container.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Container.o

# target to build an object file
Src/client/Gui/ObjectSFML/Container.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.o

Src/client/Gui/ObjectSFML/Container.i: Src/client/Gui/ObjectSFML/Container.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Container.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Container.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.i

Src/client/Gui/ObjectSFML/Container.s: Src/client/Gui/ObjectSFML/Container.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Container.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Container.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Container.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Container.cpp.s

Src/client/Gui/ObjectSFML/Sprite.o: Src/client/Gui/ObjectSFML/Sprite.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Sprite.o

# target to build an object file
Src/client/Gui/ObjectSFML/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.o

Src/client/Gui/ObjectSFML/Sprite.i: Src/client/Gui/ObjectSFML/Sprite.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Sprite.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.i

Src/client/Gui/ObjectSFML/Sprite.s: Src/client/Gui/ObjectSFML/Sprite.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Sprite.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Sprite.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Sprite.cpp.s

Src/client/Gui/ObjectSFML/Square.o: Src/client/Gui/ObjectSFML/Square.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Square.o

# target to build an object file
Src/client/Gui/ObjectSFML/Square.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.o

Src/client/Gui/ObjectSFML/Square.i: Src/client/Gui/ObjectSFML/Square.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Square.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Square.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.i

Src/client/Gui/ObjectSFML/Square.s: Src/client/Gui/ObjectSFML/Square.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Square.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Square.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Square.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Square.cpp.s

Src/client/Gui/ObjectSFML/Text.o: Src/client/Gui/ObjectSFML/Text.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/Text.o

# target to build an object file
Src/client/Gui/ObjectSFML/Text.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.o

Src/client/Gui/ObjectSFML/Text.i: Src/client/Gui/ObjectSFML/Text.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/Text.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/Text.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.i

Src/client/Gui/ObjectSFML/Text.s: Src/client/Gui/ObjectSFML/Text.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/Text.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/Text.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/Text.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/Text.cpp.s

Src/client/Gui/ObjectSFML/TextInput.o: Src/client/Gui/ObjectSFML/TextInput.cpp.o

.PHONY : Src/client/Gui/ObjectSFML/TextInput.o

# target to build an object file
Src/client/Gui/ObjectSFML/TextInput.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.o
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.o

Src/client/Gui/ObjectSFML/TextInput.i: Src/client/Gui/ObjectSFML/TextInput.cpp.i

.PHONY : Src/client/Gui/ObjectSFML/TextInput.i

# target to preprocess a source file
Src/client/Gui/ObjectSFML/TextInput.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.i
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.i

Src/client/Gui/ObjectSFML/TextInput.s: Src/client/Gui/ObjectSFML/TextInput.cpp.s

.PHONY : Src/client/Gui/ObjectSFML/TextInput.s

# target to generate assembly for a file
Src/client/Gui/ObjectSFML/TextInput.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/ObjectSFML/TextInput.cpp.s
.PHONY : Src/client/Gui/ObjectSFML/TextInput.cpp.s

Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.o: Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.o

.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.o

# target to build an object file
Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.o
.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.o

Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.i: Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.i

.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.i

# target to preprocess a source file
Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.i
.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.i

Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.s: Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.s

.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.s

# target to generate assembly for a file
Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.s
.PHONY : Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.cpp.s

Src/client/Gui/SFML_monitor.o: Src/client/Gui/SFML_monitor.cpp.o

.PHONY : Src/client/Gui/SFML_monitor.o

# target to build an object file
Src/client/Gui/SFML_monitor.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.o
.PHONY : Src/client/Gui/SFML_monitor.cpp.o

Src/client/Gui/SFML_monitor.i: Src/client/Gui/SFML_monitor.cpp.i

.PHONY : Src/client/Gui/SFML_monitor.i

# target to preprocess a source file
Src/client/Gui/SFML_monitor.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.i
.PHONY : Src/client/Gui/SFML_monitor.cpp.i

Src/client/Gui/SFML_monitor.s: Src/client/Gui/SFML_monitor.cpp.s

.PHONY : Src/client/Gui/SFML_monitor.s

# target to generate assembly for a file
Src/client/Gui/SFML_monitor.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Gui/SFML_monitor.cpp.s
.PHONY : Src/client/Gui/SFML_monitor.cpp.s

Src/client/ManageDisplay.o: Src/client/ManageDisplay.cpp.o

.PHONY : Src/client/ManageDisplay.o

# target to build an object file
Src/client/ManageDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.o
.PHONY : Src/client/ManageDisplay.cpp.o

Src/client/ManageDisplay.i: Src/client/ManageDisplay.cpp.i

.PHONY : Src/client/ManageDisplay.i

# target to preprocess a source file
Src/client/ManageDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.i
.PHONY : Src/client/ManageDisplay.cpp.i

Src/client/ManageDisplay.s: Src/client/ManageDisplay.cpp.s

.PHONY : Src/client/ManageDisplay.s

# target to generate assembly for a file
Src/client/ManageDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageDisplay.cpp.s
.PHONY : Src/client/ManageDisplay.cpp.s

Src/client/ManageServer.o: Src/client/ManageServer.cpp.o

.PHONY : Src/client/ManageServer.o

# target to build an object file
Src/client/ManageServer.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.o
.PHONY : Src/client/ManageServer.cpp.o

Src/client/ManageServer.i: Src/client/ManageServer.cpp.i

.PHONY : Src/client/ManageServer.i

# target to preprocess a source file
Src/client/ManageServer.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.i
.PHONY : Src/client/ManageServer.cpp.i

Src/client/ManageServer.s: Src/client/ManageServer.cpp.s

.PHONY : Src/client/ManageServer.s

# target to generate assembly for a file
Src/client/ManageServer.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/ManageServer.cpp.s
.PHONY : Src/client/ManageServer.cpp.s

Src/client/Map.o: Src/client/Map.cpp.o

.PHONY : Src/client/Map.o

# target to build an object file
Src/client/Map.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.o
.PHONY : Src/client/Map.cpp.o

Src/client/Map.i: Src/client/Map.cpp.i

.PHONY : Src/client/Map.i

# target to preprocess a source file
Src/client/Map.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.i
.PHONY : Src/client/Map.cpp.i

Src/client/Map.s: Src/client/Map.cpp.s

.PHONY : Src/client/Map.s

# target to generate assembly for a file
Src/client/Map.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Map.cpp.s
.PHONY : Src/client/Map.cpp.s

Src/client/Texture/GuiTexture.o: Src/client/Texture/GuiTexture.cpp.o

.PHONY : Src/client/Texture/GuiTexture.o

# target to build an object file
Src/client/Texture/GuiTexture.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/GuiTexture.cpp.o
.PHONY : Src/client/Texture/GuiTexture.cpp.o

Src/client/Texture/GuiTexture.i: Src/client/Texture/GuiTexture.cpp.i

.PHONY : Src/client/Texture/GuiTexture.i

# target to preprocess a source file
Src/client/Texture/GuiTexture.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/GuiTexture.cpp.i
.PHONY : Src/client/Texture/GuiTexture.cpp.i

Src/client/Texture/GuiTexture.s: Src/client/Texture/GuiTexture.cpp.s

.PHONY : Src/client/Texture/GuiTexture.s

# target to generate assembly for a file
Src/client/Texture/GuiTexture.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/GuiTexture.cpp.s
.PHONY : Src/client/Texture/GuiTexture.cpp.s

Src/client/Texture/IATexture.o: Src/client/Texture/IATexture.cpp.o

.PHONY : Src/client/Texture/IATexture.o

# target to build an object file
Src/client/Texture/IATexture.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/IATexture.cpp.o
.PHONY : Src/client/Texture/IATexture.cpp.o

Src/client/Texture/IATexture.i: Src/client/Texture/IATexture.cpp.i

.PHONY : Src/client/Texture/IATexture.i

# target to preprocess a source file
Src/client/Texture/IATexture.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/IATexture.cpp.i
.PHONY : Src/client/Texture/IATexture.cpp.i

Src/client/Texture/IATexture.s: Src/client/Texture/IATexture.cpp.s

.PHONY : Src/client/Texture/IATexture.s

# target to generate assembly for a file
Src/client/Texture/IATexture.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/IATexture.cpp.s
.PHONY : Src/client/Texture/IATexture.cpp.s

Src/client/Texture/shackTexture.o: Src/client/Texture/shackTexture.cpp.o

.PHONY : Src/client/Texture/shackTexture.o

# target to build an object file
Src/client/Texture/shackTexture.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/shackTexture.cpp.o
.PHONY : Src/client/Texture/shackTexture.cpp.o

Src/client/Texture/shackTexture.i: Src/client/Texture/shackTexture.cpp.i

.PHONY : Src/client/Texture/shackTexture.i

# target to preprocess a source file
Src/client/Texture/shackTexture.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/shackTexture.cpp.i
.PHONY : Src/client/Texture/shackTexture.cpp.i

Src/client/Texture/shackTexture.s: Src/client/Texture/shackTexture.cpp.s

.PHONY : Src/client/Texture/shackTexture.s

# target to generate assembly for a file
Src/client/Texture/shackTexture.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/Src/client/Texture/shackTexture.cpp.s
.PHONY : Src/client/Texture/shackTexture.cpp.s

src/server/ai_protocol/broadcast.o: src/server/ai_protocol/broadcast.c.o

.PHONY : src/server/ai_protocol/broadcast.o

# target to build an object file
src/server/ai_protocol/broadcast.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/broadcast.c.o
.PHONY : src/server/ai_protocol/broadcast.c.o

src/server/ai_protocol/broadcast.i: src/server/ai_protocol/broadcast.c.i

.PHONY : src/server/ai_protocol/broadcast.i

# target to preprocess a source file
src/server/ai_protocol/broadcast.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/broadcast.c.i
.PHONY : src/server/ai_protocol/broadcast.c.i

src/server/ai_protocol/broadcast.s: src/server/ai_protocol/broadcast.c.s

.PHONY : src/server/ai_protocol/broadcast.s

# target to generate assembly for a file
src/server/ai_protocol/broadcast.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/broadcast.c.s
.PHONY : src/server/ai_protocol/broadcast.c.s

src/server/ai_protocol/connect_nbr.o: src/server/ai_protocol/connect_nbr.c.o

.PHONY : src/server/ai_protocol/connect_nbr.o

# target to build an object file
src/server/ai_protocol/connect_nbr.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/connect_nbr.c.o
.PHONY : src/server/ai_protocol/connect_nbr.c.o

src/server/ai_protocol/connect_nbr.i: src/server/ai_protocol/connect_nbr.c.i

.PHONY : src/server/ai_protocol/connect_nbr.i

# target to preprocess a source file
src/server/ai_protocol/connect_nbr.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/connect_nbr.c.i
.PHONY : src/server/ai_protocol/connect_nbr.c.i

src/server/ai_protocol/connect_nbr.s: src/server/ai_protocol/connect_nbr.c.s

.PHONY : src/server/ai_protocol/connect_nbr.s

# target to generate assembly for a file
src/server/ai_protocol/connect_nbr.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/connect_nbr.c.s
.PHONY : src/server/ai_protocol/connect_nbr.c.s

src/server/ai_protocol/die.o: src/server/ai_protocol/die.c.o

.PHONY : src/server/ai_protocol/die.o

# target to build an object file
src/server/ai_protocol/die.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/die.c.o
.PHONY : src/server/ai_protocol/die.c.o

src/server/ai_protocol/die.i: src/server/ai_protocol/die.c.i

.PHONY : src/server/ai_protocol/die.i

# target to preprocess a source file
src/server/ai_protocol/die.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/die.c.i
.PHONY : src/server/ai_protocol/die.c.i

src/server/ai_protocol/die.s: src/server/ai_protocol/die.c.s

.PHONY : src/server/ai_protocol/die.s

# target to generate assembly for a file
src/server/ai_protocol/die.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/die.c.s
.PHONY : src/server/ai_protocol/die.c.s

src/server/ai_protocol/eject.o: src/server/ai_protocol/eject.c.o

.PHONY : src/server/ai_protocol/eject.o

# target to build an object file
src/server/ai_protocol/eject.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/eject.c.o
.PHONY : src/server/ai_protocol/eject.c.o

src/server/ai_protocol/eject.i: src/server/ai_protocol/eject.c.i

.PHONY : src/server/ai_protocol/eject.i

# target to preprocess a source file
src/server/ai_protocol/eject.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/eject.c.i
.PHONY : src/server/ai_protocol/eject.c.i

src/server/ai_protocol/eject.s: src/server/ai_protocol/eject.c.s

.PHONY : src/server/ai_protocol/eject.s

# target to generate assembly for a file
src/server/ai_protocol/eject.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/eject.c.s
.PHONY : src/server/ai_protocol/eject.c.s

src/server/ai_protocol/fork.o: src/server/ai_protocol/fork.c.o

.PHONY : src/server/ai_protocol/fork.o

# target to build an object file
src/server/ai_protocol/fork.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/fork.c.o
.PHONY : src/server/ai_protocol/fork.c.o

src/server/ai_protocol/fork.i: src/server/ai_protocol/fork.c.i

.PHONY : src/server/ai_protocol/fork.i

# target to preprocess a source file
src/server/ai_protocol/fork.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/fork.c.i
.PHONY : src/server/ai_protocol/fork.c.i

src/server/ai_protocol/fork.s: src/server/ai_protocol/fork.c.s

.PHONY : src/server/ai_protocol/fork.s

# target to generate assembly for a file
src/server/ai_protocol/fork.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/fork.c.s
.PHONY : src/server/ai_protocol/fork.c.s

src/server/ai_protocol/incantation.o: src/server/ai_protocol/incantation.c.o

.PHONY : src/server/ai_protocol/incantation.o

# target to build an object file
src/server/ai_protocol/incantation.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/incantation.c.o
.PHONY : src/server/ai_protocol/incantation.c.o

src/server/ai_protocol/incantation.i: src/server/ai_protocol/incantation.c.i

.PHONY : src/server/ai_protocol/incantation.i

# target to preprocess a source file
src/server/ai_protocol/incantation.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/incantation.c.i
.PHONY : src/server/ai_protocol/incantation.c.i

src/server/ai_protocol/incantation.s: src/server/ai_protocol/incantation.c.s

.PHONY : src/server/ai_protocol/incantation.s

# target to generate assembly for a file
src/server/ai_protocol/incantation.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/incantation.c.s
.PHONY : src/server/ai_protocol/incantation.c.s

src/server/ai_protocol/inventory.o: src/server/ai_protocol/inventory.c.o

.PHONY : src/server/ai_protocol/inventory.o

# target to build an object file
src/server/ai_protocol/inventory.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/inventory.c.o
.PHONY : src/server/ai_protocol/inventory.c.o

src/server/ai_protocol/inventory.i: src/server/ai_protocol/inventory.c.i

.PHONY : src/server/ai_protocol/inventory.i

# target to preprocess a source file
src/server/ai_protocol/inventory.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/inventory.c.i
.PHONY : src/server/ai_protocol/inventory.c.i

src/server/ai_protocol/inventory.s: src/server/ai_protocol/inventory.c.s

.PHONY : src/server/ai_protocol/inventory.s

# target to generate assembly for a file
src/server/ai_protocol/inventory.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/inventory.c.s
.PHONY : src/server/ai_protocol/inventory.c.s

src/server/ai_protocol/look.o: src/server/ai_protocol/look.c.o

.PHONY : src/server/ai_protocol/look.o

# target to build an object file
src/server/ai_protocol/look.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/look.c.o
.PHONY : src/server/ai_protocol/look.c.o

src/server/ai_protocol/look.i: src/server/ai_protocol/look.c.i

.PHONY : src/server/ai_protocol/look.i

# target to preprocess a source file
src/server/ai_protocol/look.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/look.c.i
.PHONY : src/server/ai_protocol/look.c.i

src/server/ai_protocol/look.s: src/server/ai_protocol/look.c.s

.PHONY : src/server/ai_protocol/look.s

# target to generate assembly for a file
src/server/ai_protocol/look.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/look.c.s
.PHONY : src/server/ai_protocol/look.c.s

src/server/ai_protocol/movement.o: src/server/ai_protocol/movement.c.o

.PHONY : src/server/ai_protocol/movement.o

# target to build an object file
src/server/ai_protocol/movement.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/movement.c.o
.PHONY : src/server/ai_protocol/movement.c.o

src/server/ai_protocol/movement.i: src/server/ai_protocol/movement.c.i

.PHONY : src/server/ai_protocol/movement.i

# target to preprocess a source file
src/server/ai_protocol/movement.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/movement.c.i
.PHONY : src/server/ai_protocol/movement.c.i

src/server/ai_protocol/movement.s: src/server/ai_protocol/movement.c.s

.PHONY : src/server/ai_protocol/movement.s

# target to generate assembly for a file
src/server/ai_protocol/movement.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/movement.c.s
.PHONY : src/server/ai_protocol/movement.c.s

src/server/ai_protocol/set.o: src/server/ai_protocol/set.c.o

.PHONY : src/server/ai_protocol/set.o

# target to build an object file
src/server/ai_protocol/set.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/set.c.o
.PHONY : src/server/ai_protocol/set.c.o

src/server/ai_protocol/set.i: src/server/ai_protocol/set.c.i

.PHONY : src/server/ai_protocol/set.i

# target to preprocess a source file
src/server/ai_protocol/set.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/set.c.i
.PHONY : src/server/ai_protocol/set.c.i

src/server/ai_protocol/set.s: src/server/ai_protocol/set.c.s

.PHONY : src/server/ai_protocol/set.s

# target to generate assembly for a file
src/server/ai_protocol/set.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/set.c.s
.PHONY : src/server/ai_protocol/set.c.s

src/server/ai_protocol/take.o: src/server/ai_protocol/take.c.o

.PHONY : src/server/ai_protocol/take.o

# target to build an object file
src/server/ai_protocol/take.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/take.c.o
.PHONY : src/server/ai_protocol/take.c.o

src/server/ai_protocol/take.i: src/server/ai_protocol/take.c.i

.PHONY : src/server/ai_protocol/take.i

# target to preprocess a source file
src/server/ai_protocol/take.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/take.c.i
.PHONY : src/server/ai_protocol/take.c.i

src/server/ai_protocol/take.s: src/server/ai_protocol/take.c.s

.PHONY : src/server/ai_protocol/take.s

# target to generate assembly for a file
src/server/ai_protocol/take.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/ai_protocol/take.c.s
.PHONY : src/server/ai_protocol/take.c.s

src/server/client_manager/egg.o: src/server/client_manager/egg.c.o

.PHONY : src/server/client_manager/egg.o

# target to build an object file
src/server/client_manager/egg.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/egg.c.o
.PHONY : src/server/client_manager/egg.c.o

src/server/client_manager/egg.i: src/server/client_manager/egg.c.i

.PHONY : src/server/client_manager/egg.i

# target to preprocess a source file
src/server/client_manager/egg.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/egg.c.i
.PHONY : src/server/client_manager/egg.c.i

src/server/client_manager/egg.s: src/server/client_manager/egg.c.s

.PHONY : src/server/client_manager/egg.s

# target to generate assembly for a file
src/server/client_manager/egg.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/egg.c.s
.PHONY : src/server/client_manager/egg.c.s

src/server/client_manager/join.o: src/server/client_manager/join.c.o

.PHONY : src/server/client_manager/join.o

# target to build an object file
src/server/client_manager/join.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/join.c.o
.PHONY : src/server/client_manager/join.c.o

src/server/client_manager/join.i: src/server/client_manager/join.c.i

.PHONY : src/server/client_manager/join.i

# target to preprocess a source file
src/server/client_manager/join.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/join.c.i
.PHONY : src/server/client_manager/join.c.i

src/server/client_manager/join.s: src/server/client_manager/join.c.s

.PHONY : src/server/client_manager/join.s

# target to generate assembly for a file
src/server/client_manager/join.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/join.c.s
.PHONY : src/server/client_manager/join.c.s

src/server/client_manager/leave.o: src/server/client_manager/leave.c.o

.PHONY : src/server/client_manager/leave.o

# target to build an object file
src/server/client_manager/leave.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/leave.c.o
.PHONY : src/server/client_manager/leave.c.o

src/server/client_manager/leave.i: src/server/client_manager/leave.c.i

.PHONY : src/server/client_manager/leave.i

# target to preprocess a source file
src/server/client_manager/leave.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/leave.c.i
.PHONY : src/server/client_manager/leave.c.i

src/server/client_manager/leave.s: src/server/client_manager/leave.c.s

.PHONY : src/server/client_manager/leave.s

# target to generate assembly for a file
src/server/client_manager/leave.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/leave.c.s
.PHONY : src/server/client_manager/leave.c.s

src/server/client_manager/manager.o: src/server/client_manager/manager.c.o

.PHONY : src/server/client_manager/manager.o

# target to build an object file
src/server/client_manager/manager.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/manager.c.o
.PHONY : src/server/client_manager/manager.c.o

src/server/client_manager/manager.i: src/server/client_manager/manager.c.i

.PHONY : src/server/client_manager/manager.i

# target to preprocess a source file
src/server/client_manager/manager.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/manager.c.i
.PHONY : src/server/client_manager/manager.c.i

src/server/client_manager/manager.s: src/server/client_manager/manager.c.s

.PHONY : src/server/client_manager/manager.s

# target to generate assembly for a file
src/server/client_manager/manager.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/manager.c.s
.PHONY : src/server/client_manager/manager.c.s

src/server/client_manager/msg_queue.o: src/server/client_manager/msg_queue.c.o

.PHONY : src/server/client_manager/msg_queue.o

# target to build an object file
src/server/client_manager/msg_queue.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/msg_queue.c.o
.PHONY : src/server/client_manager/msg_queue.c.o

src/server/client_manager/msg_queue.i: src/server/client_manager/msg_queue.c.i

.PHONY : src/server/client_manager/msg_queue.i

# target to preprocess a source file
src/server/client_manager/msg_queue.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/msg_queue.c.i
.PHONY : src/server/client_manager/msg_queue.c.i

src/server/client_manager/msg_queue.s: src/server/client_manager/msg_queue.c.s

.PHONY : src/server/client_manager/msg_queue.s

# target to generate assembly for a file
src/server/client_manager/msg_queue.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/msg_queue.c.s
.PHONY : src/server/client_manager/msg_queue.c.s

src/server/client_manager/orientation.o: src/server/client_manager/orientation.c.o

.PHONY : src/server/client_manager/orientation.o

# target to build an object file
src/server/client_manager/orientation.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/orientation.c.o
.PHONY : src/server/client_manager/orientation.c.o

src/server/client_manager/orientation.i: src/server/client_manager/orientation.c.i

.PHONY : src/server/client_manager/orientation.i

# target to preprocess a source file
src/server/client_manager/orientation.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/orientation.c.i
.PHONY : src/server/client_manager/orientation.c.i

src/server/client_manager/orientation.s: src/server/client_manager/orientation.c.s

.PHONY : src/server/client_manager/orientation.s

# target to generate assembly for a file
src/server/client_manager/orientation.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/orientation.c.s
.PHONY : src/server/client_manager/orientation.c.s

src/server/client_manager/teams.o: src/server/client_manager/teams.c.o

.PHONY : src/server/client_manager/teams.o

# target to build an object file
src/server/client_manager/teams.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/teams.c.o
.PHONY : src/server/client_manager/teams.c.o

src/server/client_manager/teams.i: src/server/client_manager/teams.c.i

.PHONY : src/server/client_manager/teams.i

# target to preprocess a source file
src/server/client_manager/teams.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/teams.c.i
.PHONY : src/server/client_manager/teams.c.i

src/server/client_manager/teams.s: src/server/client_manager/teams.c.s

.PHONY : src/server/client_manager/teams.s

# target to generate assembly for a file
src/server/client_manager/teams.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/client_manager/teams.c.s
.PHONY : src/server/client_manager/teams.c.s

src/server/debug.o: src/server/debug.c.o

.PHONY : src/server/debug.o

# target to build an object file
src/server/debug.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/debug.c.o
.PHONY : src/server/debug.c.o

src/server/debug.i: src/server/debug.c.i

.PHONY : src/server/debug.i

# target to preprocess a source file
src/server/debug.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/debug.c.i
.PHONY : src/server/debug.c.i

src/server/debug.s: src/server/debug.c.s

.PHONY : src/server/debug.s

# target to generate assembly for a file
src/server/debug.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/debug.c.s
.PHONY : src/server/debug.c.s

src/server/grahic_protocol/action.o: src/server/grahic_protocol/action.c.o

.PHONY : src/server/grahic_protocol/action.o

# target to build an object file
src/server/grahic_protocol/action.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/action.c.o
.PHONY : src/server/grahic_protocol/action.c.o

src/server/grahic_protocol/action.i: src/server/grahic_protocol/action.c.i

.PHONY : src/server/grahic_protocol/action.i

# target to preprocess a source file
src/server/grahic_protocol/action.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/action.c.i
.PHONY : src/server/grahic_protocol/action.c.i

src/server/grahic_protocol/action.s: src/server/grahic_protocol/action.c.s

.PHONY : src/server/grahic_protocol/action.s

# target to generate assembly for a file
src/server/grahic_protocol/action.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/action.c.s
.PHONY : src/server/grahic_protocol/action.c.s

src/server/grahic_protocol/egg.o: src/server/grahic_protocol/egg.c.o

.PHONY : src/server/grahic_protocol/egg.o

# target to build an object file
src/server/grahic_protocol/egg.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/egg.c.o
.PHONY : src/server/grahic_protocol/egg.c.o

src/server/grahic_protocol/egg.i: src/server/grahic_protocol/egg.c.i

.PHONY : src/server/grahic_protocol/egg.i

# target to preprocess a source file
src/server/grahic_protocol/egg.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/egg.c.i
.PHONY : src/server/grahic_protocol/egg.c.i

src/server/grahic_protocol/egg.s: src/server/grahic_protocol/egg.c.s

.PHONY : src/server/grahic_protocol/egg.s

# target to generate assembly for a file
src/server/grahic_protocol/egg.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/egg.c.s
.PHONY : src/server/grahic_protocol/egg.c.s

src/server/grahic_protocol/io.o: src/server/grahic_protocol/io.c.o

.PHONY : src/server/grahic_protocol/io.o

# target to build an object file
src/server/grahic_protocol/io.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/io.c.o
.PHONY : src/server/grahic_protocol/io.c.o

src/server/grahic_protocol/io.i: src/server/grahic_protocol/io.c.i

.PHONY : src/server/grahic_protocol/io.i

# target to preprocess a source file
src/server/grahic_protocol/io.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/io.c.i
.PHONY : src/server/grahic_protocol/io.c.i

src/server/grahic_protocol/io.s: src/server/grahic_protocol/io.c.s

.PHONY : src/server/grahic_protocol/io.s

# target to generate assembly for a file
src/server/grahic_protocol/io.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/io.c.s
.PHONY : src/server/grahic_protocol/io.c.s

src/server/grahic_protocol/map.o: src/server/grahic_protocol/map.c.o

.PHONY : src/server/grahic_protocol/map.o

# target to build an object file
src/server/grahic_protocol/map.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/map.c.o
.PHONY : src/server/grahic_protocol/map.c.o

src/server/grahic_protocol/map.i: src/server/grahic_protocol/map.c.i

.PHONY : src/server/grahic_protocol/map.i

# target to preprocess a source file
src/server/grahic_protocol/map.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/map.c.i
.PHONY : src/server/grahic_protocol/map.c.i

src/server/grahic_protocol/map.s: src/server/grahic_protocol/map.c.s

.PHONY : src/server/grahic_protocol/map.s

# target to generate assembly for a file
src/server/grahic_protocol/map.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/map.c.s
.PHONY : src/server/grahic_protocol/map.c.s

src/server/grahic_protocol/player.o: src/server/grahic_protocol/player.c.o

.PHONY : src/server/grahic_protocol/player.o

# target to build an object file
src/server/grahic_protocol/player.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/player.c.o
.PHONY : src/server/grahic_protocol/player.c.o

src/server/grahic_protocol/player.i: src/server/grahic_protocol/player.c.i

.PHONY : src/server/grahic_protocol/player.i

# target to preprocess a source file
src/server/grahic_protocol/player.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/player.c.i
.PHONY : src/server/grahic_protocol/player.c.i

src/server/grahic_protocol/player.s: src/server/grahic_protocol/player.c.s

.PHONY : src/server/grahic_protocol/player.s

# target to generate assembly for a file
src/server/grahic_protocol/player.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/player.c.s
.PHONY : src/server/grahic_protocol/player.c.s

src/server/grahic_protocol/quantification.o: src/server/grahic_protocol/quantification.c.o

.PHONY : src/server/grahic_protocol/quantification.o

# target to build an object file
src/server/grahic_protocol/quantification.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/quantification.c.o
.PHONY : src/server/grahic_protocol/quantification.c.o

src/server/grahic_protocol/quantification.i: src/server/grahic_protocol/quantification.c.i

.PHONY : src/server/grahic_protocol/quantification.i

# target to preprocess a source file
src/server/grahic_protocol/quantification.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/quantification.c.i
.PHONY : src/server/grahic_protocol/quantification.c.i

src/server/grahic_protocol/quantification.s: src/server/grahic_protocol/quantification.c.s

.PHONY : src/server/grahic_protocol/quantification.s

# target to generate assembly for a file
src/server/grahic_protocol/quantification.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/quantification.c.s
.PHONY : src/server/grahic_protocol/quantification.c.s

src/server/grahic_protocol/server.o: src/server/grahic_protocol/server.c.o

.PHONY : src/server/grahic_protocol/server.o

# target to build an object file
src/server/grahic_protocol/server.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/server.c.o
.PHONY : src/server/grahic_protocol/server.c.o

src/server/grahic_protocol/server.i: src/server/grahic_protocol/server.c.i

.PHONY : src/server/grahic_protocol/server.i

# target to preprocess a source file
src/server/grahic_protocol/server.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/server.c.i
.PHONY : src/server/grahic_protocol/server.c.i

src/server/grahic_protocol/server.s: src/server/grahic_protocol/server.c.s

.PHONY : src/server/grahic_protocol/server.s

# target to generate assembly for a file
src/server/grahic_protocol/server.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/server.c.s
.PHONY : src/server/grahic_protocol/server.c.s

src/server/grahic_protocol/status.o: src/server/grahic_protocol/status.c.o

.PHONY : src/server/grahic_protocol/status.o

# target to build an object file
src/server/grahic_protocol/status.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/status.c.o
.PHONY : src/server/grahic_protocol/status.c.o

src/server/grahic_protocol/status.i: src/server/grahic_protocol/status.c.i

.PHONY : src/server/grahic_protocol/status.i

# target to preprocess a source file
src/server/grahic_protocol/status.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/status.c.i
.PHONY : src/server/grahic_protocol/status.c.i

src/server/grahic_protocol/status.s: src/server/grahic_protocol/status.c.s

.PHONY : src/server/grahic_protocol/status.s

# target to generate assembly for a file
src/server/grahic_protocol/status.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/grahic_protocol/status.c.s
.PHONY : src/server/grahic_protocol/status.c.s

src/server/gui_manager/command.o: src/server/gui_manager/command.c.o

.PHONY : src/server/gui_manager/command.o

# target to build an object file
src/server/gui_manager/command.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/command.c.o
.PHONY : src/server/gui_manager/command.c.o

src/server/gui_manager/command.i: src/server/gui_manager/command.c.i

.PHONY : src/server/gui_manager/command.i

# target to preprocess a source file
src/server/gui_manager/command.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/command.c.i
.PHONY : src/server/gui_manager/command.c.i

src/server/gui_manager/command.s: src/server/gui_manager/command.c.s

.PHONY : src/server/gui_manager/command.s

# target to generate assembly for a file
src/server/gui_manager/command.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/command.c.s
.PHONY : src/server/gui_manager/command.c.s

src/server/gui_manager/manager.o: src/server/gui_manager/manager.c.o

.PHONY : src/server/gui_manager/manager.o

# target to build an object file
src/server/gui_manager/manager.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/manager.c.o
.PHONY : src/server/gui_manager/manager.c.o

src/server/gui_manager/manager.i: src/server/gui_manager/manager.c.i

.PHONY : src/server/gui_manager/manager.i

# target to preprocess a source file
src/server/gui_manager/manager.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/manager.c.i
.PHONY : src/server/gui_manager/manager.c.i

src/server/gui_manager/manager.s: src/server/gui_manager/manager.c.s

.PHONY : src/server/gui_manager/manager.s

# target to generate assembly for a file
src/server/gui_manager/manager.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/gui_manager/manager.c.s
.PHONY : src/server/gui_manager/manager.c.s

src/server/loop.o: src/server/loop.c.o

.PHONY : src/server/loop.o

# target to build an object file
src/server/loop.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/loop.c.o
.PHONY : src/server/loop.c.o

src/server/loop.i: src/server/loop.c.i

.PHONY : src/server/loop.i

# target to preprocess a source file
src/server/loop.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/loop.c.i
.PHONY : src/server/loop.c.i

src/server/loop.s: src/server/loop.c.s

.PHONY : src/server/loop.s

# target to generate assembly for a file
src/server/loop.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/loop.c.s
.PHONY : src/server/loop.c.s

src/server/main.o: src/server/main.c.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/main.c.o
.PHONY : src/server/main.c.o

src/server/main.i: src/server/main.c.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/main.c.i
.PHONY : src/server/main.c.i

src/server/main.s: src/server/main.c.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/main.c.s
.PHONY : src/server/main.c.s

src/server/map.o: src/server/map.c.o

.PHONY : src/server/map.o

# target to build an object file
src/server/map.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/map.c.o
.PHONY : src/server/map.c.o

src/server/map.i: src/server/map.c.i

.PHONY : src/server/map.i

# target to preprocess a source file
src/server/map.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/map.c.i
.PHONY : src/server/map.c.i

src/server/map.s: src/server/map.c.s

.PHONY : src/server/map.s

# target to generate assembly for a file
src/server/map.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/map.c.s
.PHONY : src/server/map.c.s

src/server/parsing/game.o: src/server/parsing/game.c.o

.PHONY : src/server/parsing/game.o

# target to build an object file
src/server/parsing/game.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/game.c.o
.PHONY : src/server/parsing/game.c.o

src/server/parsing/game.i: src/server/parsing/game.c.i

.PHONY : src/server/parsing/game.i

# target to preprocess a source file
src/server/parsing/game.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/game.c.i
.PHONY : src/server/parsing/game.c.i

src/server/parsing/game.s: src/server/parsing/game.c.s

.PHONY : src/server/parsing/game.s

# target to generate assembly for a file
src/server/parsing/game.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/game.c.s
.PHONY : src/server/parsing/game.c.s

src/server/parsing/gnl.o: src/server/parsing/gnl.c.o

.PHONY : src/server/parsing/gnl.o

# target to build an object file
src/server/parsing/gnl.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/gnl.c.o
.PHONY : src/server/parsing/gnl.c.o

src/server/parsing/gnl.i: src/server/parsing/gnl.c.i

.PHONY : src/server/parsing/gnl.i

# target to preprocess a source file
src/server/parsing/gnl.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/gnl.c.i
.PHONY : src/server/parsing/gnl.c.i

src/server/parsing/gnl.s: src/server/parsing/gnl.c.s

.PHONY : src/server/parsing/gnl.s

# target to generate assembly for a file
src/server/parsing/gnl.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/gnl.c.s
.PHONY : src/server/parsing/gnl.c.s

src/server/parsing/parser.o: src/server/parsing/parser.c.o

.PHONY : src/server/parsing/parser.o

# target to build an object file
src/server/parsing/parser.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/parser.c.o
.PHONY : src/server/parsing/parser.c.o

src/server/parsing/parser.i: src/server/parsing/parser.c.i

.PHONY : src/server/parsing/parser.i

# target to preprocess a source file
src/server/parsing/parser.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/parser.c.i
.PHONY : src/server/parsing/parser.c.i

src/server/parsing/parser.s: src/server/parsing/parser.c.s

.PHONY : src/server/parsing/parser.s

# target to generate assembly for a file
src/server/parsing/parser.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/parser.c.s
.PHONY : src/server/parsing/parser.c.s

src/server/parsing/port.o: src/server/parsing/port.c.o

.PHONY : src/server/parsing/port.o

# target to build an object file
src/server/parsing/port.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/port.c.o
.PHONY : src/server/parsing/port.c.o

src/server/parsing/port.i: src/server/parsing/port.c.i

.PHONY : src/server/parsing/port.i

# target to preprocess a source file
src/server/parsing/port.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/port.c.i
.PHONY : src/server/parsing/port.c.i

src/server/parsing/port.s: src/server/parsing/port.c.s

.PHONY : src/server/parsing/port.s

# target to generate assembly for a file
src/server/parsing/port.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/parsing/port.c.s
.PHONY : src/server/parsing/port.c.s

src/server/scheduler/add.o: src/server/scheduler/add.c.o

.PHONY : src/server/scheduler/add.o

# target to build an object file
src/server/scheduler/add.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/add.c.o
.PHONY : src/server/scheduler/add.c.o

src/server/scheduler/add.i: src/server/scheduler/add.c.i

.PHONY : src/server/scheduler/add.i

# target to preprocess a source file
src/server/scheduler/add.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/add.c.i
.PHONY : src/server/scheduler/add.c.i

src/server/scheduler/add.s: src/server/scheduler/add.c.s

.PHONY : src/server/scheduler/add.s

# target to generate assembly for a file
src/server/scheduler/add.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/add.c.s
.PHONY : src/server/scheduler/add.c.s

src/server/scheduler/scheduler.o: src/server/scheduler/scheduler.c.o

.PHONY : src/server/scheduler/scheduler.o

# target to build an object file
src/server/scheduler/scheduler.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/scheduler.c.o
.PHONY : src/server/scheduler/scheduler.c.o

src/server/scheduler/scheduler.i: src/server/scheduler/scheduler.c.i

.PHONY : src/server/scheduler/scheduler.i

# target to preprocess a source file
src/server/scheduler/scheduler.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/scheduler.c.i
.PHONY : src/server/scheduler/scheduler.c.i

src/server/scheduler/scheduler.s: src/server/scheduler/scheduler.c.s

.PHONY : src/server/scheduler/scheduler.s

# target to generate assembly for a file
src/server/scheduler/scheduler.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/scheduler/scheduler.c.s
.PHONY : src/server/scheduler/scheduler.c.s

src/server/server.o: src/server/server.c.o

.PHONY : src/server/server.o

# target to build an object file
src/server/server.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/server.c.o
.PHONY : src/server/server.c.o

src/server/server.i: src/server/server.c.i

.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/server.c.i
.PHONY : src/server/server.c.i

src/server/server.s: src/server/server.c.s

.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/server.c.s
.PHONY : src/server/server.c.s

src/server/socket/socket.o: src/server/socket/socket.c.o

.PHONY : src/server/socket/socket.o

# target to build an object file
src/server/socket/socket.c.o:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/socket/socket.c.o
.PHONY : src/server/socket/socket.c.o

src/server/socket/socket.i: src/server/socket/socket.c.i

.PHONY : src/server/socket/socket.i

# target to preprocess a source file
src/server/socket/socket.c.i:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/socket/socket.c.i
.PHONY : src/server/socket/socket.c.i

src/server/socket/socket.s: src/server/socket/socket.c.s

.PHONY : src/server/socket/socket.s

# target to generate assembly for a file
src/server/socket/socket.c.s:
	$(MAKE) -f CMakeFiles/zappy_server.dir/build.make CMakeFiles/zappy_server.dir/src/server/socket/socket.c.s
.PHONY : src/server/socket/socket.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... zappy_server"
	@echo "... Src/CstringArray.o"
	@echo "... Src/CstringArray.i"
	@echo "... Src/CstringArray.s"
	@echo "... Src/Entity/AMotionShape.o"
	@echo "... Src/Entity/AMotionShape.i"
	@echo "... Src/Entity/AMotionShape.s"
	@echo "... Src/Entity/ARectangleShape.o"
	@echo "... Src/Entity/ARectangleShape.i"
	@echo "... Src/Entity/ARectangleShape.s"
	@echo "... Src/Entity/Cell.o"
	@echo "... Src/Entity/Cell.i"
	@echo "... Src/Entity/Cell.s"
	@echo "... Src/Entity/Character.o"
	@echo "... Src/Entity/Character.i"
	@echo "... Src/Entity/Character.s"
	@echo "... Src/Entity/Water.o"
	@echo "... Src/Entity/Water.i"
	@echo "... Src/Entity/Water.s"
	@echo "... Src/Grid.o"
	@echo "... Src/Grid.i"
	@echo "... Src/Grid.s"
	@echo "... Src/Main.o"
	@echo "... Src/Main.i"
	@echo "... Src/Main.s"
	@echo "... Src/ParseEnqueueMap.o"
	@echo "... Src/ParseEnqueueMap.i"
	@echo "... Src/ParseEnqueueMap.s"
	@echo "... Src/SfmlTool.o"
	@echo "... Src/SfmlTool.i"
	@echo "... Src/SfmlTool.s"
	@echo "... Src/Text/AText.o"
	@echo "... Src/Text/AText.i"
	@echo "... Src/Text/AText.s"
	@echo "... Src/Text/GameText.o"
	@echo "... Src/Text/GameText.i"
	@echo "... Src/Text/GameText.s"
	@echo "... Src/Tools/Thread.o"
	@echo "... Src/Tools/Thread.i"
	@echo "... Src/Tools/Thread.s"
	@echo "... Src/WindowInfo.o"
	@echo "... Src/WindowInfo.i"
	@echo "... Src/WindowInfo.s"
	@echo "... Src/client/Auth.o"
	@echo "... Src/client/Auth.i"
	@echo "... Src/client/Auth.s"
	@echo "... Src/client/Communication.o"
	@echo "... Src/client/Communication.i"
	@echo "... Src/client/Communication.s"
	@echo "... Src/client/Gui.o"
	@echo "... Src/client/Gui.i"
	@echo "... Src/client/Gui.s"
	@echo "... Src/client/Gui/Animation/Modal.o"
	@echo "... Src/client/Gui/Animation/Modal.i"
	@echo "... Src/client/Gui/Animation/Modal.s"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.o"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.i"
	@echo "... Src/client/Gui/ObjectSFML/AbstractObjectSFML.s"
	@echo "... Src/client/Gui/ObjectSFML/Circle.o"
	@echo "... Src/client/Gui/ObjectSFML/Circle.i"
	@echo "... Src/client/Gui/ObjectSFML/Circle.s"
	@echo "... Src/client/Gui/ObjectSFML/Container.o"
	@echo "... Src/client/Gui/ObjectSFML/Container.i"
	@echo "... Src/client/Gui/ObjectSFML/Container.s"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.o"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.i"
	@echo "... Src/client/Gui/ObjectSFML/Sprite.s"
	@echo "... Src/client/Gui/ObjectSFML/Square.o"
	@echo "... Src/client/Gui/ObjectSFML/Square.i"
	@echo "... Src/client/Gui/ObjectSFML/Square.s"
	@echo "... Src/client/Gui/ObjectSFML/Text.o"
	@echo "... Src/client/Gui/ObjectSFML/Text.i"
	@echo "... Src/client/Gui/ObjectSFML/Text.s"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.o"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.i"
	@echo "... Src/client/Gui/ObjectSFML/TextInput.s"
	@echo "... Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.o"
	@echo "... Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.i"
	@echo "... Src/client/Gui/PersonalizedObject/TextInputBckPlaceHorder.s"
	@echo "... Src/client/Gui/SFML_monitor.o"
	@echo "... Src/client/Gui/SFML_monitor.i"
	@echo "... Src/client/Gui/SFML_monitor.s"
	@echo "... Src/client/ManageDisplay.o"
	@echo "... Src/client/ManageDisplay.i"
	@echo "... Src/client/ManageDisplay.s"
	@echo "... Src/client/ManageServer.o"
	@echo "... Src/client/ManageServer.i"
	@echo "... Src/client/ManageServer.s"
	@echo "... Src/client/Map.o"
	@echo "... Src/client/Map.i"
	@echo "... Src/client/Map.s"
	@echo "... Src/client/Texture/GuiTexture.o"
	@echo "... Src/client/Texture/GuiTexture.i"
	@echo "... Src/client/Texture/GuiTexture.s"
	@echo "... Src/client/Texture/IATexture.o"
	@echo "... Src/client/Texture/IATexture.i"
	@echo "... Src/client/Texture/IATexture.s"
	@echo "... Src/client/Texture/shackTexture.o"
	@echo "... Src/client/Texture/shackTexture.i"
	@echo "... Src/client/Texture/shackTexture.s"
	@echo "... src/server/ai_protocol/broadcast.o"
	@echo "... src/server/ai_protocol/broadcast.i"
	@echo "... src/server/ai_protocol/broadcast.s"
	@echo "... src/server/ai_protocol/connect_nbr.o"
	@echo "... src/server/ai_protocol/connect_nbr.i"
	@echo "... src/server/ai_protocol/connect_nbr.s"
	@echo "... src/server/ai_protocol/die.o"
	@echo "... src/server/ai_protocol/die.i"
	@echo "... src/server/ai_protocol/die.s"
	@echo "... src/server/ai_protocol/eject.o"
	@echo "... src/server/ai_protocol/eject.i"
	@echo "... src/server/ai_protocol/eject.s"
	@echo "... src/server/ai_protocol/fork.o"
	@echo "... src/server/ai_protocol/fork.i"
	@echo "... src/server/ai_protocol/fork.s"
	@echo "... src/server/ai_protocol/incantation.o"
	@echo "... src/server/ai_protocol/incantation.i"
	@echo "... src/server/ai_protocol/incantation.s"
	@echo "... src/server/ai_protocol/inventory.o"
	@echo "... src/server/ai_protocol/inventory.i"
	@echo "... src/server/ai_protocol/inventory.s"
	@echo "... src/server/ai_protocol/look.o"
	@echo "... src/server/ai_protocol/look.i"
	@echo "... src/server/ai_protocol/look.s"
	@echo "... src/server/ai_protocol/movement.o"
	@echo "... src/server/ai_protocol/movement.i"
	@echo "... src/server/ai_protocol/movement.s"
	@echo "... src/server/ai_protocol/set.o"
	@echo "... src/server/ai_protocol/set.i"
	@echo "... src/server/ai_protocol/set.s"
	@echo "... src/server/ai_protocol/take.o"
	@echo "... src/server/ai_protocol/take.i"
	@echo "... src/server/ai_protocol/take.s"
	@echo "... src/server/client_manager/egg.o"
	@echo "... src/server/client_manager/egg.i"
	@echo "... src/server/client_manager/egg.s"
	@echo "... src/server/client_manager/join.o"
	@echo "... src/server/client_manager/join.i"
	@echo "... src/server/client_manager/join.s"
	@echo "... src/server/client_manager/leave.o"
	@echo "... src/server/client_manager/leave.i"
	@echo "... src/server/client_manager/leave.s"
	@echo "... src/server/client_manager/manager.o"
	@echo "... src/server/client_manager/manager.i"
	@echo "... src/server/client_manager/manager.s"
	@echo "... src/server/client_manager/msg_queue.o"
	@echo "... src/server/client_manager/msg_queue.i"
	@echo "... src/server/client_manager/msg_queue.s"
	@echo "... src/server/client_manager/orientation.o"
	@echo "... src/server/client_manager/orientation.i"
	@echo "... src/server/client_manager/orientation.s"
	@echo "... src/server/client_manager/teams.o"
	@echo "... src/server/client_manager/teams.i"
	@echo "... src/server/client_manager/teams.s"
	@echo "... src/server/debug.o"
	@echo "... src/server/debug.i"
	@echo "... src/server/debug.s"
	@echo "... src/server/grahic_protocol/action.o"
	@echo "... src/server/grahic_protocol/action.i"
	@echo "... src/server/grahic_protocol/action.s"
	@echo "... src/server/grahic_protocol/egg.o"
	@echo "... src/server/grahic_protocol/egg.i"
	@echo "... src/server/grahic_protocol/egg.s"
	@echo "... src/server/grahic_protocol/io.o"
	@echo "... src/server/grahic_protocol/io.i"
	@echo "... src/server/grahic_protocol/io.s"
	@echo "... src/server/grahic_protocol/map.o"
	@echo "... src/server/grahic_protocol/map.i"
	@echo "... src/server/grahic_protocol/map.s"
	@echo "... src/server/grahic_protocol/player.o"
	@echo "... src/server/grahic_protocol/player.i"
	@echo "... src/server/grahic_protocol/player.s"
	@echo "... src/server/grahic_protocol/quantification.o"
	@echo "... src/server/grahic_protocol/quantification.i"
	@echo "... src/server/grahic_protocol/quantification.s"
	@echo "... src/server/grahic_protocol/server.o"
	@echo "... src/server/grahic_protocol/server.i"
	@echo "... src/server/grahic_protocol/server.s"
	@echo "... src/server/grahic_protocol/status.o"
	@echo "... src/server/grahic_protocol/status.i"
	@echo "... src/server/grahic_protocol/status.s"
	@echo "... src/server/gui_manager/command.o"
	@echo "... src/server/gui_manager/command.i"
	@echo "... src/server/gui_manager/command.s"
	@echo "... src/server/gui_manager/manager.o"
	@echo "... src/server/gui_manager/manager.i"
	@echo "... src/server/gui_manager/manager.s"
	@echo "... src/server/loop.o"
	@echo "... src/server/loop.i"
	@echo "... src/server/loop.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/map.o"
	@echo "... src/server/map.i"
	@echo "... src/server/map.s"
	@echo "... src/server/parsing/game.o"
	@echo "... src/server/parsing/game.i"
	@echo "... src/server/parsing/game.s"
	@echo "... src/server/parsing/gnl.o"
	@echo "... src/server/parsing/gnl.i"
	@echo "... src/server/parsing/gnl.s"
	@echo "... src/server/parsing/parser.o"
	@echo "... src/server/parsing/parser.i"
	@echo "... src/server/parsing/parser.s"
	@echo "... src/server/parsing/port.o"
	@echo "... src/server/parsing/port.i"
	@echo "... src/server/parsing/port.s"
	@echo "... src/server/scheduler/add.o"
	@echo "... src/server/scheduler/add.i"
	@echo "... src/server/scheduler/add.s"
	@echo "... src/server/scheduler/scheduler.o"
	@echo "... src/server/scheduler/scheduler.i"
	@echo "... src/server/scheduler/scheduler.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/server/socket/socket.o"
	@echo "... src/server/socket/socket.i"
	@echo "... src/server/socket/socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

