#!/usr/bin/env python3
# coding: utf-8

import sys
from socket import error as sockerror
from Ai_Client.Client.Client import Client, ZappyException


def usage(code=0):
    print("USAGE: %s -p port -n name -h machine" % (sys.argv[0]))
    print("\tport\tis the port number")
    print("\tname\tis the name of the team")
    print("\tmachine\tis the name of the machine; localhost by default")
    sys.exit(code)


def run(port: int, name: str, machine: str):
    print("Running in team '%s' on port %d as machine '%s'" % (name, port, machine))
    client = Client(port, name, machine)
    if client.connect():
        client.run()
    else:
        return


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-help":
        usage(1)
    port = int(-1)
    name = ""
    machine = "localhost"
    try:
        i = 1
        while i < len(sys.argv):
            if sys.argv[i] == "-p":
                port = int(sys.argv[i + 1])
                i += 1
            elif sys.argv[i] == "-n":
                name = sys.argv[i + 1]
                i += 1
            elif sys.argv[i] == "-h":
                machine = sys.argv[i + 1]
                i += 1
            else:
                usage(84)
            i += 1
    except (ValueError, IndexError):
        usage(84)
    if len(name) == 0 or port < 0:
        usage(84)
    try:
        run(port, name, machine)
    except (sockerror, ZappyException) as err:
        sys.stderr.write(str(err) + "\n")
        exit(84)


if __name__ == "__main__":
    main()
